[profile.default]
src = 'contracts'
out = 'artifacts'
gas_reports = [
    "VeArtProxy",
    "VotingEscrow",
    "Voter",
    "Gauge",
    "Minter",
    "Pool",
    "RewardsDistributor",
    "Router"
]

fs_permissions = [{ access = "read-write", path = "./"}]

[rpc_endpoints]
goerli = "${GOERLI_RPC_URL}"
optimism = "${OPTIMISM_RPC_URL}"

[etherscan]
es_goerli = { key = "${GOERLI_SCAN_API_KEY}", url = "${GOERLI_ETHERSCAN_VERIFIER_URL}" }
es_optimism = { key = "${OPTIMISM_SCAN_API_KEY}", url = "${OPTIMISM_ETHERSCAN_VERIFIER_URL}" }