[profile.default]
src = 'contracts'
out = 'artifacts'
gas_reports = [
    "VotingEscrow",
    "Voter",
    "Gauge",
    "Minter",
    "Pair",
    "RewardsDistributor",
    "Router"
]

fs_permissions = [{ access = "read", path = "./"}]

[rpc_endpoints]
goerli = "${GOERLI_RPC_URL}"
optimism = "${OPTIMISM_RPC_URL}"

[etherscan]
goerli = { key = "${OP_SCAN_API_KEY}" }
optimism = { key = "${OP_SCAN_API_KEY}" }