name: CI

on:
  push:
    branches: [ contracts-v2 ]
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: "Build the contracts and print their size"
        run: |
          forge --version
          forge build --sizes

      - name: Run tests
        run: forge test -vvv
        env:
          OPTIMISM_RPC_URL: ${{ secrets.OPTIMISM_RPC_URL }}
          PRIVATE_KEY_DEPLOY: ${{ secrets.PRIVATE_KEY_DEPLOY }}
          CONSTANTS_FILENAME: ${{ secrets.CONSTANTS_FILENAME }}
          OUTPUT_FILENAME: ${{ secrets.OUTPUT_FILENAME }}
          
      - name: slither-static-analysis
        continue-on-error: true
        uses: luisfontes19/slither-static-analysis-action@v0.3.4
      
